{% set name = "vector-vis-graph" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vector_vis_graph-{{ version }}.tar.gz
  sha256: 655fbeb8cc6b923d11596e649223494318194a4738f9b11c2c1b9ef7128f96cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.12
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10,<3.12
    - numpy >=1.26.2,<2.0.0
    - numba >=0.58.1,<0.59.0
    - scipy >=1.11.4,<2.0.0

test:
  imports:
    - vector_vis_graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tunakasif/vector-vis-graph
  summary: Vector visibility graph generation from multivariate time series.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tunakasif
