{% set python_min = "3.10" %}
{% set name = "vector-vis-graph" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vector_vis_graph-{{ version }}.tar.gz
  sha256: bc10225131177c79755dc5c26bf9d8962071a3ea5f41a46c6ecb3b23588ccdb7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<3.12
    - numpy >=1.26.2,<2.0.0
    - numba >=0.58.1,<0.59.0
    - scipy >=1.11.4,<2.0.0

test:
  imports:
    - vector_vis_graph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tunakasif/vector-vis-graph
  summary: Vector visibility graph generation from multivariate time series.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tunakasif
